/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */

plugins{
    `java-library`
}

repositories{
    mavenCentral()
}

dependencies{
     implementation("com.google.code.gson:gson:2.10.1")
}

tasks {
  withType<Jar> {
        manifest {
            attributes["Main-Class"] = "com.kuta.Main" 
        }
        configurations["compileClasspath"].forEach { file: File ->
        from(zipTree(file.absoluteFile))
    }
    }
}